version: "3"

services:
  angular_app:
    build: .
    ports:
      - "4200:4200"
      - "3001:3001"
    #environment:
    #  - CHOKIDAR_USEPOLLING=true
    #  - NODE_ENV=dev
    volumes:
      - "./src:/src"
      - "nodemodules:/workspaces/src/kaonet-app/node_modules"

volumes:
  nodemodules:
    driver: "local"
# https://anytimesnotes.com/archives/246
