version: "3"

services:
  angular_app:
    build: .
    tty: true
    ports:
      - "4200:4200"
      - "3001:3001"
    #environment:
    #  - CHOKIDAR_USEPOLLING=true
    #  - NODE_ENV=dev
    volumes:
      - node_data:/workspace/node_modules
      - ../:/workspace:cached

volumes:
  node_data:
    driver: "local"
# https://anytimesnotes.com/archives/246
